[font]
size = 12.0

[font.normal]
# On Windows: "JetBrainsMono Nerd Font"
family = "JetBrains Mono Nerd Font"

[colors.normal]
black   = "#282828"
blue    = "#458588"
cyan    = "#689d6a"
green   = "#98971a"
magenta = "#b16286"
red     = "#cc241d"
white   = "#a89984"
yellow  = "#d79921"

[colors.bright]
black   = "#928374"
blue    = "#83a598"
cyan    = "#8ec07c"
green   = "#b8bb26"
magenta = "#d3869b"
red     = "#fb4934"
white   = "#ebdbb2"
yellow  = "#fabd2f"

[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

[mouse]
hide_when_typing = true

[window]
decorations = "none"

[keyboard]
bindings = [
    { key = "Return",         action = "ToggleFullscreen", mods = "Alt"           },
    { key = "F11",            action = "ToggleFullscreen"                         },
    { key = "V",              action = "Paste",            mods = "Control|Shift" },
    { key = "C",              action = "Copy",             mods = "Control|Shift" },
    { key = "Insert",         action = "PasteSelection",   mods = "Shift"         },
    { key = "Plus",           action = "IncreaseFontSize", mods = "Control"       },
    { key = "Minus",          action = "DecreaseFontSize", mods = "Control"       },
    { key = "Key0",           action = "ResetFontSize",    mods = "Control"       },
    { key = "NumpadAdd",      action = "IncreaseFontSize", mods = "Control"       },
    { key = "NumpadSubtract", action = "DecreaseFontSize", mods = "Control"       },
    { key = "Numpad0",        action = "ResetFontSize",    mods = "Control"       },
]

