require("custom.plugins")
require('impatient')

require("custom.mappings")
require("custom.general")
require("custom.utils")

require("plugins.comment")
require("plugins.fidget")
require("plugins.gitsigns")
require("plugins.goyo")
require("plugins.gruvbox")
require("plugins.harpoon")
require("plugins.lualine")
require("plugins.null-ls")
require("plugins.nvim-autopairs")
require("plugins.nvim-cmp")
require("plugins.nvim-dap")
require("plugins.nvim-lsp-installer")
require("plugins.nvim-lspconfig")
require("plugins.nvim-tree")
require("plugins.nvim-surround")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.trouble")
require("plugins.vim-better-whitespace")
require("plugins.vim-checkbox")
